name: tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: esLint
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
        run: npm ci
        run: make lint